/**
 * BookendChainer — auto-invokes `/epic-close` when the run began with
 * `epic::auto-close`. `/epic-code-review` and `epic-retro helper` always remain
 * operator-driven (they are listed in the hand-off comment regardless) so that
 * autonomous closure is a single, explicit action rather than a chain of
 * review/retro/close that could mask unexamined work.
 *
 * Authorization is a snapshot: the `autoClose` boolean is captured at
 * dispatch time (recorded in the `epic-run-state` checkpoint) and passed in
 * here. Applying the `epic::auto-close` label mid-run is ignored; removing
 * it mid-run is also ignored. This prevents post-hoc authorization of a
 * merge-to-main that includes unexamined work.
 *
 * When `autoClose=false` the chainer posts a hand-off comment listing all
 * remaining skills the operator must drive manually, then exits cleanly.
 *
 * When `autoClose=true` the chainer invokes `/epic-close` via a
 * caller-supplied `runSkill` adapter. If no adapter is available it degrades
 * to a hand-off comment that explicitly calls out the manual step.
 */

const AUTO_CLOSE_STEP = '/epic-close';
const OPERATOR_HANDOFF_STEPS = [
  '/epic-code-review',
  'epic-retro helper',
  AUTO_CLOSE_STEP,
];

export class BookendChainer {
  /**
   * @param {{
   *   autoClose: boolean,
   *   epicId: number,
   *   runSkill?: (skill: string, args: { epicId: number }) => Promise<{ status: 'ok'|'failed', detail?: string }>,
   *   postComment?: (ticketId: number, payload: object) => Promise<unknown>,
   *   logger?: { info: Function, warn: Function },
   *   errorJournal?: { record: Function, path: string },
   * }} opts
   */
  constructor(opts = {}) {
    const ctx = opts.ctx;
    const epicId = opts.epicId ?? ctx?.epicId;
    if (!Number.isInteger(epicId)) {
      throw new TypeError('BookendChainer requires a numeric epicId');
    }
    this.autoClose = Boolean(opts.autoClose);
    this.epicId = epicId;
    this.runSkill = opts.runSkill ?? ctx?.runSkill;
    this.postComment = opts.postComment;
    this.logger = opts.logger ?? ctx?.logger ?? console;
    this.errorJournal = opts.errorJournal ?? ctx?.errorJournal ?? null;
  }

  #journalSuffix() {
    return this.errorJournal?.path ? ` (see ${this.errorJournal.path})` : '';
  }

  async run() {
    if (!this.autoClose) {
      await this.#postHandoff();
      return { executed: false, reason: 'autoClose-disabled' };
    }

    if (typeof this.runSkill !== 'function') {
      this.logger.warn?.(
        '[BookendChainer] autoClose=true but no runSkill adapter was provided — ' +
          'bookends skipped. Operator must drive them manually.',
      );
      await this.#postHandoff('missing-runSkill');
      return { executed: false, reason: 'no-runSkill' };
    }

    // Auto-close fires only `/epic-close`. Review + retro remain operator
    // steps even when auto-close is authorized, so review artefacts are never
    // silently generated by the runner.
    this.logger.info?.(
      `[BookendChainer] running ${AUTO_CLOSE_STEP} for Epic #${this.epicId}`,
    );
    let outcome;
    try {
      outcome = await this.runSkill(AUTO_CLOSE_STEP, { epicId: this.epicId });
    } catch (err) {
      outcome = { status: 'failed', detail: err?.message ?? String(err) };
      await this.errorJournal?.record({
        module: 'BookendChainer',
        op: `runSkill(${AUTO_CLOSE_STEP})`,
        error: err,
        recovery: 'reported-as-failed',
      });
    }
    const results = [{ skill: AUTO_CLOSE_STEP, ...outcome }];
    if (outcome.status !== 'ok') {
      this.logger.warn?.(
        `[BookendChainer] ${AUTO_CLOSE_STEP} halted: ${outcome.detail ?? 'unknown error'}`,
      );
      await this.#postFailure(AUTO_CLOSE_STEP, outcome, results);
      return { executed: true, completed: false, results };
    }
    return { executed: true, completed: true, results };
  }

  async #postHandoff(extra) {
    if (typeof this.postComment !== 'function') return;
    const lines = [
      '### ✅ Epic reached `agent::review`',
      '',
      'Autonomous bookend chain not authorized — operator must drive:',
      ...OPERATOR_HANDOFF_STEPS.map((s) => `- \`${s}\``),
    ];
    if (extra) lines.push('', `_Note: ${extra}_`);
    try {
      await this.postComment(this.epicId, {
        type: 'notification',
        body: lines.join('\n'),
      });
    } catch (err) {
      this.logger.warn?.(
        `[BookendChainer] hand-off comment failed: ${err?.message ?? err}${this.#journalSuffix()}`,
      );
      await this.errorJournal?.record({
        module: 'BookendChainer',
        op: 'postComment(handoff)',
        error: err,
        recovery: 'swallowed',
      });
    }
  }

  async #postFailure(skill, outcome, results) {
    if (typeof this.postComment !== 'function') return;
    const body = [
      `### ⚠️ Autonomous bookend chain halted at \`${skill}\``,
      '',
      outcome.detail ? `Reason: \`${outcome.detail}\`` : 'Reason: unknown',
      '',
      '**Completed steps:**',
      ...results
        .filter((r) => r.status === 'ok')
        .map((r) => `- \`${r.skill}\``),
      '',
      'Operator should inspect the failure and re-run the remaining skills manually.',
    ];
    try {
      await this.postComment(this.epicId, {
        type: 'friction',
        body: body.join('\n'),
      });
    } catch (err) {
      this.logger.warn?.(
        `[BookendChainer] failure comment post failed: ${err?.message ?? err}${this.#journalSuffix()}`,
      );
      await this.errorJournal?.record({
        module: 'BookendChainer',
        op: 'postComment(failure)',
        error: err,
        recovery: 'swallowed',
      });
    }
  }
}
