/**
 * Guided-onboard doc scaffolder: find the configured
 * `project.docsContextFiles` missing under the docs root and, when `write`,
 * stub each one (from `.agents/templates/docs/<name>` when shipped, else a
 * generic placeholder). `write: false` is a side-effect-free preview.
 *
 * @module lib/onboard/scaffold-docs
 */

import fsDefault from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getPaths, resolveConfig } from '../config-resolver.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// scripts/lib/onboard/ → scripts/lib/ → scripts/ → .agents/
const AGENT_ROOT = path.resolve(__dirname, '../../..');
const DOCS_TEMPLATE_DIR = path.join(AGENT_ROOT, 'templates', 'docs');

/**
 * Marker in every stub; the `/mandrel-plan` first-run preflight detects
 * unedited stubs by this exact string — changing it is a hard cutover.
 *
 * @type {string}
 */
export const STUB_MARKER = '<!-- MANDREL:STUB -->';

/**
 * @param {string} fileName - e.g. `data-dictionary.md`
 * @returns {string}
 */
function genericStub(fileName) {
  const base = fileName.replace(/\.[^.]+$/, '');
  const title = base
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
  return (
    `${STUB_MARKER}\n` +
    `# ${title}\n\n` +
    '> **Stub generated by `mandrel init`.** This file is one of the\n' +
    '> `project.docsContextFiles` mandatory-reads — agents load it before\n' +
    '> every task. Replace this placeholder with real content.\n'
  );
}

/**
 * @param {string} fileName
 * @param {import('node:fs')} fsImpl
 * @returns {string}
 */
function stubContentFor(fileName, fsImpl) {
  const templatePath = path.join(DOCS_TEMPLATE_DIR, fileName);
  if (fsImpl.existsSync(templatePath)) {
    const body = fsImpl.readFileSync(templatePath, 'utf8');
    // Templates stay marker-free so they read cleanly as documentation.
    return body.startsWith(STUB_MARKER) ? body : `${STUB_MARKER}\n${body}`;
  }
  return genericStub(fileName);
}

/**
 * @param {object} [opts]
 * @param {string} [opts.root] - Project root to resolve config + docs root
 *   against.
 * @param {string[]} [opts.docsContextFiles] - Override the configured list.
 * @param {string} [opts.docsRoot] - Override the docs-root directory name.
 * @param {boolean} [opts.write=true] - `false` only detects.
 * @param {import('node:fs')} [opts.fs] - Injectable fs implementation.
 * @returns {{
 *   docsRoot: string,
 *   docsContextFiles: string[],
 *   missing: string[],
 *   present: string[],
 *   created: string[],
 * }}
 */
export function scaffoldDocs(opts = {}) {
  const fsImpl = opts.fs ?? fsDefault;
  const write = opts.write !== false;

  const config = resolveConfig({ cwd: opts.root, ctx: { fs: fsImpl } });
  const projectRoot = path.resolve(opts.root ?? process.cwd());

  const docsContextFiles =
    opts.docsContextFiles ?? config.project.docsContextFiles ?? [];
  const docsRootName = opts.docsRoot ?? getPaths(config).docsRoot;
  const docsRootAbs = path.resolve(projectRoot, docsRootName);

  const present = [];
  const missing = [];
  for (const fileName of docsContextFiles) {
    const target = path.join(docsRootAbs, fileName);
    if (fsImpl.existsSync(target)) {
      present.push(fileName);
    } else {
      missing.push(fileName);
    }
  }

  const created = [];
  if (write && missing.length > 0) {
    fsImpl.mkdirSync(docsRootAbs, { recursive: true });
    for (const fileName of missing) {
      const target = path.join(docsRootAbs, fileName);
      fsImpl.mkdirSync(path.dirname(target), { recursive: true });
      fsImpl.writeFileSync(target, stubContentFor(fileName, fsImpl), 'utf8');
      created.push(fileName);
    }
  }

  return {
    docsRoot: docsRootAbs,
    docsContextFiles,
    missing,
    present,
    created,
  };
}
