/**
 * Defaults-inventory fidelity (Story #5007), replacing the hand-parity suite.
 *
 * `.agents/docs/agentrc-reference.json` is the sync/explain defaults SSOT via
 * `getAgentrcDefaults()`. It used to be hand-authored alongside the runtime
 * `*_DEFAULTS` constants, and this suite existed to prove the two had not
 * drifted — otherwise `/mandrel-update` and `mandrel explain` lie about what
 * an omitted key means.
 *
 * It is now generated by `generate-config-docs.js` from the `default`
 * annotations on the runtime schema literals, and most of those annotations
 * *import* the matching `*_DEFAULTS` constant, so for those keys the drift
 * class is structurally gone. What is left to police is the residue:
 *
 *   1. The on-disk inventory is what the generator emits (freshness).
 *   2. Every annotation that had to **restate** a runtime default rather than
 *      import it still agrees with that default. Four cases could not import
 *      cleanly — see `RESTATED_DEFAULTS` below — and each is a live drift
 *      risk this suite is the only guard for.
 *   3. Keys retired by the v2 cutover stay out of the inventory.
 *
 * Agent-read-only / inventory-only keys (workflows honor them; JS does not
 * resolve a parallel DEFAULT constant) are listed in
 * `AGENT_READ_ONLY_PREFIXES` and are documented, not equality-checked.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';
import { buildReferenceInventory } from '../../.agents/scripts/generate-config-docs.js';
import {
  getAgentrcDefaults,
  lookupPath,
} from '../../.agents/scripts/lib/config/defaults.js';
import { LIMITS_DEFAULTS } from '../../.agents/scripts/lib/config/limits.js';
import { getRunners } from '../../.agents/scripts/lib/config/runners.js';
import { WORKTREE_ISOLATION_DEFAULTS } from '../../.agents/scripts/lib/config/worktree-isolation.js';
import { AGENTRC_SCHEMA } from '../../.agents/scripts/lib/config-settings-schema.js';
import { WATCH_DEFAULTS } from '../../.agents/scripts/pr-watch-with-update.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REFERENCE_PATH = path.resolve(
  __dirname,
  '..',
  '..',
  '.agents',
  'docs',
  'agentrc-reference.json',
);

/** Prefixes intentionally absent from runtime *_DEFAULTS (agent/workflow-read). */
const AGENT_READ_ONLY_PREFIXES = Object.freeze([
  'project.docsContextFiles',
  'project.baseBranch',
  'planning.navigation',
  'github.owner',
  'github.repo',
  'github.projectNumber',
  'github.projectOwner',
  'github.operatorHandle',
  'github.defaultTimeoutMs',
  'delivery.docsFreshness',
  'delivery.mergeWatch',
  'delivery.feedbackLoop',
  'delivery.quality.gates.lint',
  'delivery.quality.gates.mutation',
  'delivery.quality.gates.lighthouse',
  'delivery.quality.gates.bundle-size',
  'delivery.quality.gates.duplication',
  'delivery.quality.gateScoping',
  'delivery.quality.autoRefresh',
  'delivery.quality.navigability',
  'delivery.quality.requireBaselines',
  'delivery.quality.formatAutofix',
  'delivery.codeReview.providers',
  'delivery.refactorStage',
  'qa.',
]);

function isAgentReadOnly(dottedPath) {
  return AGENT_READ_ONLY_PREFIXES.some(
    (prefix) => dottedPath === prefix || dottedPath.startsWith(`${prefix}`),
  );
}

/**
 * The `default` annotations that could NOT import their runtime constant, with
 * the reason and the live value they must equal. Everything else in the
 * inventory reads its constant directly from the schema literal, so it cannot
 * drift by construction.
 */
const RESTATED_DEFAULTS = Object.freeze([
  {
    path: 'delivery.deliverRunner.concurrencyCap',
    reason:
      'getRunners() resolves the value inline; there is no exported constant to import.',
    expected: () => getRunners({}).deliverRunner.concurrencyCap,
  },
  {
    path: 'delivery.worktreeIsolation.nodeModulesStrategy',
    reason:
      'WORKTREE_ISOLATION_DEFAULTS.nodeModulesStrategy is evaluated at import time and becomes `per-worktree` on win32; the inventory pins the cross-platform documented default.',
    expected: () => 'clone',
  },
  {
    path: 'delivery.ci.watch',
    reason:
      'WATCH_DEFAULTS lives in the pr-watch-with-update.js CLI; importing it behind a schema declaration would drag runAsCli into every config read.',
    expected: () => ({
      pollIntervalMs: WATCH_DEFAULTS.pollIntervalMs,
      maxPolls: WATCH_DEFAULTS.maxPolls,
      maxResumes: WATCH_DEFAULTS.maxResumes,
      attachWindowMs: WATCH_DEFAULTS.attachWindowMs,
    }),
  },
]);

describe('agentrc-reference.json — generator fidelity', () => {
  it('the on-disk inventory is what the generator emits from the runtime schema', () => {
    const onDisk = JSON.parse(readFileSync(REFERENCE_PATH, 'utf8'));
    assert.deepEqual(
      onDisk,
      buildReferenceInventory(AGENTRC_SCHEMA),
      'agentrc-reference.json drifted from the schema `default` annotations. Run `npm run docs:gen`.',
    );
  });

  it('getAgentrcDefaults() reads that same inventory (minus the $schema pointer)', () => {
    const expected = buildReferenceInventory(AGENTRC_SCHEMA);
    delete expected.$schema;
    assert.deepEqual(getAgentrcDefaults({ bustCache: true }), expected);
  });
});

describe('agentrc-reference.json — restated defaults still track their runtime source', () => {
  for (const { path: dotted, reason, expected } of RESTATED_DEFAULTS) {
    it(`${dotted} matches the runtime value (${reason.split('.')[0]})`, () => {
      const ref = getAgentrcDefaults({ bustCache: true });
      const found = lookupPath(ref, dotted);
      assert.equal(found.present, true, `${dotted} missing from the inventory`);
      assert.deepEqual(
        found.value,
        expected(),
        `${dotted} was restated rather than imported because: ${reason} It has now drifted from the runtime value.`,
      );
    });
  }

  it('the restated set is exhaustive for worktreeIsolation and execution', () => {
    // These blocks import their constants member-wise, so the assertion is
    // cheap insurance that the import actually reached the annotation.
    const ref = getAgentrcDefaults({ bustCache: true });
    const wi = ref.delivery.worktreeIsolation;
    assert.equal(wi.enabled, WORKTREE_ISOLATION_DEFAULTS.enabled);
    assert.equal(wi.root, WORKTREE_ISOLATION_DEFAULTS.root);
    assert.equal(wi.primeFromPath, WORKTREE_ISOLATION_DEFAULTS.primeFromPath);
    assert.equal(
      wi.allowSymlinkOnWindows,
      WORKTREE_ISOLATION_DEFAULTS.allowSymlinkOnWindows,
    );
    assert.equal(wi.reapOnSuccess, WORKTREE_ISOLATION_DEFAULTS.reapOnSuccess);
    assert.deepEqual(wi.bootstrapFiles, [
      ...WORKTREE_ISOLATION_DEFAULTS.bootstrapFiles,
    ]);
    assert.equal('reapOnCancel' in wi, false);
    assert.equal(
      ref.delivery.execution.timeoutMs,
      LIMITS_DEFAULTS.executionTimeoutMs,
    );
    assert.equal(
      ref.delivery.signals,
      undefined,
      'delivery.signals was retired in Story #5313',
    );
  });
});

describe('agentrc-reference.json — retired keys stay out', () => {
  const ref = getAgentrcDefaults({ bustCache: true });

  it('omits the retired planning.context block (Story #4541)', () => {
    // The budget it fed lost its last caller in the v2 cutover, so the key
    // resolved but capped nothing. Gone from both the runtime defaults and
    // the exhaustive reference; the schema now rejects it outright.
    assert.equal(ref.planning.context, undefined);
    assert.equal('planningContext' in LIMITS_DEFAULTS, false);
  });

  it('omits planning.modelCapacity — and the constant that replaced it is gone too (Story #5312)', () => {
    assert.equal(ref.planning.modelCapacity, undefined);
  });

  it('omits the ten planning.* keys Story #5312 retired', () => {
    for (const key of [
      'complexityGate',
      'riskHeuristics',
      'failOnSharedEditors',
      'requireExplicitCrossStoryDeps',
      'failOnRegistryConflicts',
      'failOnLargeFanOut',
      'largeFanOutThreshold',
      'crossCuttingRegistries',
    ]) {
      assert.equal(ref.planning[key], undefined, key);
    }
    assert.deepEqual(Object.keys(ref.planning.memoryPool), [
      'indexByteCeiling',
    ]);
  });

  it('omits delivery.lease (retired lease TTL — Story #5006)', () => {
    assert.equal(ref.delivery.lease, undefined);
    assert.equal('leaseTtlMs' in LIMITS_DEFAULTS, false);
  });

  it('omits delivery.maxTokenBudget (retired envelope)', () => {
    assert.equal(ref.delivery.maxTokenBudget, undefined);
    assert.equal('maxTokenBudget' in LIMITS_DEFAULTS, false);
  });

  it('rejects retired dead keys', () => {
    for (const dead of [
      'delivery.lifecycle',
      'delivery.retro',
      'delivery.failOnConcurrencyHazards',
      'delivery.signals',
      'delivery.signals.hotspot',
      'delivery.codeReview.maxFixScopeFiles',
      'delivery.routing.freshCriticSampleRate',
      'delivery.quality.codingGuardrails.cyclomaticMustFix',
      'delivery.ci.skipForStoryPushes',
      'delivery.ci.earlyPr',
      'delivery.ci.requireChecks',
      'delivery.maxTokenBudget',
      'delivery.preflight',
      'delivery.epicAudit',
      'delivery.deliverRunner.progressReportIntervalSec',
      'delivery.deliverRunner.clusterCeiling',
      'delivery.worktreeIsolation.reapOnCancel',
      'planning.taskSizing',
      'planning.context',
      'planning.codebaseSnapshot',
      'project.commands.lintBaseline',
    ]) {
      assert.equal(
        lookupPath(ref, dead).present,
        false,
        `retired key ${dead} must not appear in agentrc-reference.json`,
      );
    }
  });

  it('documents AGENT_READ_ONLY_PREFIXES so inventory keys are intentional', () => {
    assert.ok(AGENT_READ_ONLY_PREFIXES.length > 5);
    assert.ok(isAgentReadOnly('qa.featureRoot'));
  });
});
