/**
 * mandrel-catalog.js — the slash-command catalog backend, built from
 * top-level `.agents/workflows/*.md` (`helpers/` are not commands). The
 * shipped `.agents/docs/workflows.md` is generated from it and drift-gated.
 * Read-only: no GitHub I/O, no writes.
 */

import fs from 'node:fs';
import path from 'node:path';

/**
 * Frontmatter `description:` as one whitespace-collapsed line; handles both
 * inline and folded/literal block forms.
 *
 * @param {string} source — full file contents.
 * @returns {string | null}
 */
export function extractDescription(source) {
  if (typeof source !== 'string') return null;
  // Frontmatter must be the first block; tolerate a leading BOM.
  const trimmed = source.replace(/^﻿/, '');
  if (!trimmed.startsWith('---')) return null;
  const end = trimmed.indexOf('\n---', 3);
  if (end < 0) return null;
  const block = trimmed.slice(4, end);
  const lines = block.split('\n');

  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const match = /^description:\s*(.*)$/i.exec(line);
    if (!match) {
      i += 1;
      continue;
    }
    const rest = match[1].trim();
    if (/^[>|][-+]?\s*$/.test(rest) || rest === '') {
      const collected = [];
      let j = i + 1;
      while (j < lines.length) {
        const next = lines[j];
        // Stop at the next column-0 frontmatter key.
        if (/^[A-Za-z][\w-]*\s*:/.test(next)) break;
        collected.push(next.trim());
        j += 1;
      }
      const joined = collected.join(' ').replace(/\s+/g, ' ').trim();
      return joined.length > 0 ? joined : null;
    }
    return rest.replace(/\s+/g, ' ').trim();
  }
  return null;
}

/**
 * Advisory nudge for a too-short description; never blocks rendering.
 *
 * @param {string | null} description
 * @returns {boolean}
 */
export function isVagueDescription(description) {
  if (!description) return true;
  if (description.trim().length < 30) return true;
  return false;
}

/**
 * @param {string} workflowsDir — absolute path to `.agents/workflows/`.
 * @returns {Array<{ name: string, description: string | null, vague: boolean }>}
 */
export function buildCatalog(workflowsDir) {
  if (!fs.existsSync(workflowsDir)) {
    throw new Error(
      `mandrel-catalog: workflows directory not found: ${workflowsDir}`,
    );
  }
  const entries = fs.readdirSync(workflowsDir, { withFileTypes: true });
  const catalog = [];
  for (const entry of entries) {
    // Top-level files only, mirroring `sync-claude-commands.js`.
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith('.md')) continue;
    if (entry.name === 'README.md') continue;
    const filePath = path.join(workflowsDir, entry.name);
    const source = fs.readFileSync(filePath, 'utf8');
    const description = extractDescription(source);
    catalog.push({
      name: entry.name.replace(/\.md$/, ''),
      description,
      vague: isVagueDescription(description),
    });
  }
  catalog.sort((a, b) => a.name.localeCompare(b.name));
  return catalog;
}

/**
 * `loops/<name>.md` units, invoked as `/loops:<name>`; an absent `loops/`
 * directory yields `[]`, not an error.
 *
 * @param {string} workflowsDir — absolute path to `.agents/workflows/`.
 * @returns {Array<{ name: string, description: string | null, vague: boolean }>}
 */
export function buildLoopCatalog(workflowsDir) {
  const loopsDir = path.join(workflowsDir, 'loops');
  if (!fs.existsSync(loopsDir)) return [];
  const entries = fs.readdirSync(loopsDir, { withFileTypes: true });
  const catalog = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith('.md')) continue;
    if (entry.name === 'README.md') continue;
    const filePath = path.join(loopsDir, entry.name);
    const source = fs.readFileSync(filePath, 'utf8');
    const description = extractDescription(source);
    catalog.push({
      name: entry.name.replace(/\.md$/, ''),
      description,
      vague: isVagueDescription(description),
    });
  }
  catalog.sort((a, b) => a.name.localeCompare(b.name));
  return catalog;
}

/**
 * @param {Array<{ name: string, description: string | null, vague: boolean }>} catalog
 * @returns {string}
 */
export function renderCatalog(catalog) {
  if (catalog.length === 0) {
    return '# Mandrel command catalog\n\n_(no workflows found)_\n';
  }
  const rows = catalog.map((entry) => {
    const desc = entry.description ?? '_(no description)_';
    const flag = entry.vague ? ' ⚠️ vague' : '';
    return `- **/${entry.name}** — ${desc}${flag}`;
  });
  return [
    '# Mandrel command catalog',
    '',
    `Source of truth: \`.agents/workflows/\` (${catalog.length} commands).`,
    'Auto-generated by `.agents/scripts/lib/mandrel-catalog.js`.',
    '',
    ...rows,
    '',
  ].join('\n');
}
